name: Hello World

on:
  push:
    paths:
      - ".github/workflows/01_hello-world.yml"
    branches:
      - main
      - develop
jobs:
  hello-world:
    runs-on: ubuntu-24.04

    steps:
      - name: Print Hello World
        run: echo "Hello, World!"